export enum EventType {
    START="START",
    END="END",
    PLAYER="PLAYER",
    ADVANCE="ADVANCE",
    JUMP="JUMP",
    JUMP_NEXT="JUMP_NEXT",
    INITIAL_LOCATION="INITIAL_LOCATION",
    INTERMEDIATE_LOCATION="INTERMEDIATE_LOCATION",
    FINAL_LOCATION="FINAL_LOCATION",
    ROLL_DICE="ROLL_DICE",
    PURCHACE="PURCHACE",
    PAY="PAY",
    RECEIVE="RECEIVE",
    DRAW_CHEST="DRAW_CHEST",
    DRAW_CHANCE="DRAW_CHANCE",
    NOTIFICATION="NOTIFICATION",
    HOUSE_ADD="HOUSE_ADD",
    HOUSE_REMOVE="HOUSE_REMOVE",
    HOTEL_ADD="HOTEL_ADD",
    HOTEL_REMOVE="HOTEL_REMOVE"
};

export enum CellType {
    PROPERTY = "PROPERTY",
    RAILROAD = "RAILROAD",
    UTILITY = "UTILITY",
    SPECIAL = "SPECIAL",
    JAIL = "JAIL"
};

export enum ActionType {
    TRANSITION_ABS = "TRANSITION_ABS",
    TRANSITION_REL = "TRANSITION_REL",
    DEBIT_ABS = "DEBIT_ABS",
    DEBIT_REL = "DEBIT_REL",
    CREDIT_ABS = "CREDIT_ABS",
    CREDIT_REL = "CREDIT_REL",
    JAIL = "JAIL"
};

export enum ActionPrimary {
    IN = "IN",
    OUT = "OUT",
    NEXT = "NEXT",
    FROM_EACH = "FROM_EACH",
    PAY_EACH = "PAY_EACH",
    REPAIR = "REPAIR",
    GO = "GO"
};

export enum Token {
    WHEELBARROW="WHEELBARROW",
    BATTLESHIP="BATTLESHIP",
    RACECAR="RACECAR",
    THIMBLE="THIMBLE",
    SHOE="SHOE",
    DOG="DOG",
    TOPHAT="TOPHAT",
    CAT="CAT"
}
