// export enum RuleName {
//     PASS_GO_BONUS_FIELD,
//     ENABLE_GO_LANDING_BONUS,
//     ENABLE_FREE_PARKING_BONUS,
//     ENABLE_BONUS_CAP,
//     ENABLE_FINITE_RESOURCES,
//     HOUSE_AMOUNT_FIELD,
//     HOTEL_AMOUNT_FIELD,
//     ENABLE_EVEN_BUILD,
//     HOTEL_PREREQUISITE_FIELD,
//     IMPROVEMENT_DEPRECIATION_FIELD,
//     SET_COMPLETION_BONUS_FIELD,
//     ENABLE_MORTGAGE_INTEREST,
//     MORTGAGE_INTEREST_RATE_FIELD,
//     ENABLE_SPEEDING,
//     SPEED_LIMIT_FILED,
//     MAX_JAIL_TERM_FIELD,
//     BAIL_FEE_FIELD
// };

export enum EventType {
    START,
    END,
    PLAYER,
    ADVANCE,
    JUMP,
    JUMP_NEXT,
    INITIAL_LOCATION,
    INTERMEDIATE_LOCATION,
    FINAL_LOCATION,
    ROLL_DICE,
    PURCHACE,
    PAY,
    RECEIVE,
    DRAW_CHEST,
    DRAW_CHANCE,
    NOTIFICATION,
    HOUSE_ADD,
    HOUSE_REMOVE,
    HOTEL_ADD,
    HOTEL_REMOVE
};

export enum CellType {
    PROPERTY = "PROPERTY",
    RAILROAD = "RAILROAD",
    UTILITY = "UTILITY",
    SPECIAL = "SPECIAL",
    JAIL = "JAIL"
};

export enum ActionType {
    TRANSITION_ABS = "TRANSITION_ABS",
    TRANSITION_REL = "TRANSITION_REL",
    DEBIT_ABS = "DEBIT_ABS",
    DEBIT_REL = "DEBIT_REL",
    CREDIT_ABS = "CREDIT_ABS",
    CREDIT_REL = "CREDIT_REL",
    JAIL = "JAIL"
};

export enum ActionPrimary {
    IN = "IN",
    OUT = "OUT",
    NEXT = "NEXT",
    FROM_EACH = "FROM_EACH",
    PAY_EACH = "PAY_EACH",
    REPAIR = "REPAIR",
    GO = "GO"
};
